// Decompiled with JetBrains decompiler
// Type: MegaCrit.Sts2.Core.Models.RelicPools.EventRelicPool
// Assembly: sts2, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null
// MVID: DB296A8D-D1DB-4F9A-B229-9E9A5BB4D47E
// Assembly location: D:\shaluMod\ShaLuMod\_src\sts2.dll

using MegaCrit.Sts2.Core.Models.Relics;
using System.Collections.Generic;

#nullable enable
namespace MegaCrit.Sts2.Core.Models.RelicPools;

public sealed class EventRelicPool : RelicPoolModel
{
  public override string EnergyColorName => "colorless";

  protected override IEnumerable<RelicModel> GenerateAllRelics()
  {
    // ISSUE: object of a compiler-generated type is created
    return (IEnumerable<RelicModel>) new \u003C\u003Ez__ReadOnlyArray<RelicModel>(new RelicModel[142]
    {
      (RelicModel) ModelDb.Relic<AlchemicalCoffer>(),
      (RelicModel) ModelDb.Relic<ArcaneScroll>(),
      (RelicModel) ModelDb.Relic<ArchaicTooth>(),
      (RelicModel) ModelDb.Relic<Astrolabe>(),
      (RelicModel) ModelDb.Relic<BeautifulBracelet>(),
      (RelicModel) ModelDb.Relic<BigMushroom>(),
      (RelicModel) ModelDb.Relic<BiiigHug>(),
      (RelicModel) ModelDb.Relic<BingBong>(),
      (RelicModel) ModelDb.Relic<BlackBlood>(),
      (RelicModel) ModelDb.Relic<BlackStar>(),
      (RelicModel) ModelDb.Relic<BlessedAntler>(),
      (RelicModel) ModelDb.Relic<BloodSoakedRose>(),
      (RelicModel) ModelDb.Relic<BoneTea>(),
      (RelicModel) ModelDb.Relic<BoomingConch>(),
      (RelicModel) ModelDb.Relic<BrilliantScarf>(),
      (RelicModel) ModelDb.Relic<Byrdpip>(),
      (RelicModel) ModelDb.Relic<CallingBell>(),
      (RelicModel) ModelDb.Relic<ChoicesParadox>(),
      (RelicModel) ModelDb.Relic<ChosenCheese>(),
      (RelicModel) ModelDb.Relic<Claws>(),
      (RelicModel) ModelDb.Relic<Crossbow>(),
      (RelicModel) ModelDb.Relic<CursedPearl>(),
      (RelicModel) ModelDb.Relic<DarkstonePeriapt>(),
      (RelicModel) ModelDb.Relic<DaughterOfTheWind>(),
      (RelicModel) ModelDb.Relic<DelicateFrond>(),
      (RelicModel) ModelDb.Relic<DiamondDiadem>(),
      (RelicModel) ModelDb.Relic<DistinguishedCape>(),
      (RelicModel) ModelDb.Relic<DivineDestiny>(),
      (RelicModel) ModelDb.Relic<DowsingRod>(),
      (RelicModel) ModelDb.Relic<DreamCatcher>(),
      (RelicModel) ModelDb.Relic<Driftwood>(),
      (RelicModel) ModelDb.Relic<DustyTome>(),
      (RelicModel) ModelDb.Relic<Ectoplasm>(),
      (RelicModel) ModelDb.Relic<ElectricShrymp>(),
      (RelicModel) ModelDb.Relic<EmberTea>(),
      (RelicModel) ModelDb.Relic<EmptyCage>(),
      (RelicModel) ModelDb.Relic<FakeAnchor>(),
      (RelicModel) ModelDb.Relic<FakeBloodVial>(),
      (RelicModel) ModelDb.Relic<FakeHappyFlower>(),
      (RelicModel) ModelDb.Relic<FakeLeesWaffle>(),
      (RelicModel) ModelDb.Relic<FakeMango>(),
      (RelicModel) ModelDb.Relic<FakeMerchantsRug>(),
      (RelicModel) ModelDb.Relic<FakeOrichalcum>(),
      (RelicModel) ModelDb.Relic<FakeSneckoEye>(),
      (RelicModel) ModelDb.Relic<FakeStrikeDummy>(),
      (RelicModel) ModelDb.Relic<FakeVenerableTeaSet>(),
      (RelicModel) ModelDb.Relic<Fiddle>(),
      (RelicModel) ModelDb.Relic<FishingRod>(),
      (RelicModel) ModelDb.Relic<ForgottenSoul>(),
      (RelicModel) ModelDb.Relic<FragrantMushroom>(),
      (RelicModel) ModelDb.Relic<FurCoat>(),
      (RelicModel) ModelDb.Relic<GlassEye>(),
      (RelicModel) ModelDb.Relic<Glitter>(),
      (RelicModel) ModelDb.Relic<GoldenCompass>(),
      (RelicModel) ModelDb.Relic<GoldenPearl>(),
      (RelicModel) ModelDb.Relic<HandDrill>(),
      (RelicModel) ModelDb.Relic<HeftyTablet>(),
      (RelicModel) ModelDb.Relic<HistoryCourse>(),
      (RelicModel) ModelDb.Relic<InfusedCore>(),
      (RelicModel) ModelDb.Relic<IronClub>(),
      (RelicModel) ModelDb.Relic<JeweledMask>(),
      (RelicModel) ModelDb.Relic<JewelryBox>(),
      (RelicModel) ModelDb.Relic<Kaleidoscope>(),
      (RelicModel) ModelDb.Relic<LargeCapsule>(),
      (RelicModel) ModelDb.Relic<LastingCandy>(),
      (RelicModel) ModelDb.Relic<LavaRock>(),
      (RelicModel) ModelDb.Relic<LeadPaperweight>(),
      (RelicModel) ModelDb.Relic<LeafyPoultice>(),
      (RelicModel) ModelDb.Relic<LordsParasol>(),
      (RelicModel) ModelDb.Relic<LostCoffer>(),
      (RelicModel) ModelDb.Relic<LostWisp>(),
      (RelicModel) ModelDb.Relic<MassiveScroll>(),
      (RelicModel) ModelDb.Relic<MawBank>(),
      (RelicModel) ModelDb.Relic<MeatCleaver>(),
      (RelicModel) ModelDb.Relic<MrStruggles>(),
      (RelicModel) ModelDb.Relic<MusicBox>(),
      (RelicModel) ModelDb.Relic<NeowsBones>(),
      (RelicModel) ModelDb.Relic<NeowsSacrifice>(),
      (RelicModel) ModelDb.Relic<NeowsTalisman>(),
      (RelicModel) ModelDb.Relic<NeowsTorment>(),
      (RelicModel) ModelDb.Relic<NewLeaf>(),
      (RelicModel) ModelDb.Relic<NutritiousOyster>(),
      (RelicModel) ModelDb.Relic<NutritiousSoup>(),
      (RelicModel) ModelDb.Relic<PaelsBlood>(),
      (RelicModel) ModelDb.Relic<PaelsClaw>(),
      (RelicModel) ModelDb.Relic<PaelsEye>(),
      (RelicModel) ModelDb.Relic<PaelsFlesh>(),
      (RelicModel) ModelDb.Relic<PaelsGrowth>(),
      (RelicModel) ModelDb.Relic<PaelsHorn>(),
      (RelicModel) ModelDb.Relic<PaelsLegion>(),
      (RelicModel) ModelDb.Relic<PaelsTears>(),
      (RelicModel) ModelDb.Relic<PaelsTooth>(),
      (RelicModel) ModelDb.Relic<PaelsWing>(),
      (RelicModel) ModelDb.Relic<PandorasBox>(),
      (RelicModel) ModelDb.Relic<PhialHolster>(),
      (RelicModel) ModelDb.Relic<PhilosophersStone>(),
      (RelicModel) ModelDb.Relic<PhylacteryUnbound>(),
      (RelicModel) ModelDb.Relic<PollinousCore>(),
      (RelicModel) ModelDb.Relic<Pomander>(),
      (RelicModel) ModelDb.Relic<PrecariousShears>(),
      (RelicModel) ModelDb.Relic<PreciseScissors>(),
      (RelicModel) ModelDb.Relic<PreservedFog>(),
      (RelicModel) ModelDb.Relic<PrismaticGem>(),
      (RelicModel) ModelDb.Relic<PumpkinCandle>(),
      (RelicModel) ModelDb.Relic<RadiantPearl>(),
      (RelicModel) ModelDb.Relic<RazorTooth>(),
      (RelicModel) ModelDb.Relic<RingOfTheDrake>(),
      (RelicModel) ModelDb.Relic<RoyalPoison>(),
      (RelicModel) ModelDb.Relic<RunicPyramid>(),
      (RelicModel) ModelDb.Relic<Sai>(),
      (RelicModel) ModelDb.Relic<SandCastle>(),
      (RelicModel) ModelDb.Relic<ScrollBoxes>(),
      (RelicModel) ModelDb.Relic<SeaGlass>(),
      (RelicModel) ModelDb.Relic<SealOfGold>(),
      (RelicModel) ModelDb.Relic<SereTalon>(),
      (RelicModel) ModelDb.Relic<SignetRing>(),
      (RelicModel) ModelDb.Relic<SilkenTress>(),
      (RelicModel) ModelDb.Relic<SilverCrucible>(),
      (RelicModel) ModelDb.Relic<SmallCapsule>(),
      (RelicModel) ModelDb.Relic<SneckoEye>(),
      (RelicModel) ModelDb.Relic<Sozu>(),
      (RelicModel) ModelDb.Relic<SparklingRouge>(),
      (RelicModel) ModelDb.Relic<SpikedGauntlets>(),
      (RelicModel) ModelDb.Relic<StoneHumidifier>(),
      (RelicModel) ModelDb.Relic<Storybook>(),
      (RelicModel) ModelDb.Relic<SwordOfJade>(),
      (RelicModel) ModelDb.Relic<SwordOfStone>(),
      (RelicModel) ModelDb.Relic<TanxsWhistle>(),
      (RelicModel) ModelDb.Relic<TeaOfDiscourtesy>(),
      (RelicModel) ModelDb.Relic<TheBoot>(),
      (RelicModel) ModelDb.Relic<ThrowingAxe>(),
      (RelicModel) ModelDb.Relic<ToastyMittens>(),
      (RelicModel) ModelDb.Relic<TouchOfOrobas>(),
      (RelicModel) ModelDb.Relic<ToyBox>(),
      (RelicModel) ModelDb.Relic<TriBoomerang>(),
      (RelicModel) ModelDb.Relic<VelvetChoker>(),
      (RelicModel) ModelDb.Relic<WarHammer>(),
      (RelicModel) ModelDb.Relic<WhisperingEarring>(),
      (RelicModel) ModelDb.Relic<WingedBoots>(),
      (RelicModel) ModelDb.Relic<WongoCustomerAppreciationBadge>(),
      (RelicModel) ModelDb.Relic<WongosMysteryTicket>(),
      (RelicModel) ModelDb.Relic<YummyCookie>()
    });
  }
}
